import type { Pet } from './utils/pets';
import type { GuestMessage } from '@shared/social/guestbook';

export type Phase = 'frontispiece' | 'picker' | 'processing' | 'result' | 'wall' | 'bestiary';

export interface PetShot {
  /** Local id (cuid-ish), unique per save. */
  id: string;
  /** Pet catalog id. */
  petId: string;
  /** Pet display name copied for posterity (saved before user could
   *  re-render the result later in another locale). */
  petName: string;
  /** URL of the generated AI image (platform R2). */
  imageUrl: string;
  /** URL of the original selfie upload — kept so the user can see the
   *  before/after on their own gallery. Not shown to other users. */
  selfieUrl: string;
  /** Society's one-sentence justification for assigning this order.
   *  Generated by chat API in parallel with img2img — feels personal
   *  even though species selection is currently random. */
  judgment?: string;
  createdAt: number;
}

export interface PetSave {
  shots: PetShot[];
  /** Album-Cover-Gen style reactions map: shotId → kinds. */
  reactions?: Record<string, ReactionKind[]>;
  /** In-game guestbook — public text notes left on plates (the artifact
   *  is a PetShot, keyed by shot.id). Lives in the SENDER's own blob;
   *  cross-user display is best-effort, the author is pinged via notify.
   *  See @shared/social/guestbook. */
  messages?: GuestMessage[];
}

export type ReactionKind = 'heart' | 'fire' | 'mind' | 'eye';

export interface WallEntry {
  userId: string;
  userName?: string;
  userAvatarUrl?: string;
  shot: PetShot;
}

export type { Pet };
