import type { PetFilterCartridge } from './types';
import { createNaturalistSpeciesPack } from './naturalistSpecies';

const naturalistImagePrompt = {
  hybridPrefix:
    'A 19th-century zoological plate of a HYBRID creature — mostly the ' +
    'species, with the person from the reference photo recognizable ' +
    'underneath only on careful inspection. ' +
    'CRITICAL ANCHOR: The EYES must remain UNMISTAKABLY HUMAN — ' +
    'forward-facing, almond-shape, with visible white SCLERA, eyelids, ' +
    'eyebrows, and an expressive human gaze. DO NOT replace them with ' +
    'full animal eyes. Keep HUMAN SHOULDERS and the broad face shape ' +
    'visible. Transform their head this way: ',
  hybridSuffixGuard:
    ' Balance: animal features dominate the surface (~70%), but human ' +
    'eyes + brow ridge + jawline + shoulders anchor identity (~30%). ' +
    'DO NOT include any plaque, ID number, or written text in the image.',
  styleSuffix:
    ' The result must read as a HYBRID portrait — half-human, half-creature — ' +
    'NOT as a pure animal. The viewer must still recognize the original person. ' +
    'Centered head-and-shoulders bust, naturalist\'s observation pose. ' +
    'Rendered as a 19th-century zoological plate from a natural history book ' +
    '— hand-colored lithograph or engraving, fine pen-and-ink linework with ' +
    'soft watercolor wash, in the painterly tradition of John James Audubon ' +
    'and Ernst Haeckel. Aged cream paper background with faint foxing and ' +
    'subtle paper texture, muted earthen palette of sepia, sage green, dusty ' +
    'rose, and ivory, hand-painted color washes over crisp linework. ' +
    'Painterly, traditional — no plastic sheen, no photography, no 3D render, ' +
    'no neon, no digital glow. 1:1 aspect, no text, no labels, no logos, no border.',
  variationAxes: {
    pose: [
      'three-quarter profile view',
      'frontal observation pose',
      'head turned slightly to the left',
      'head turned slightly to the right',
      'chin tilted gently upward',
      'gaze cast slightly downward',
    ],
    light: [
      'soft morning light from the upper left',
      'warm evening glow from the right',
      'diffuse overcast museum lighting',
      'cool north-window naturalist lamp',
      'amber lantern light, faint shadow',
    ],
    composition: [
      'a sprig of botanical specimens (ferns) in the lower margin',
      'a small marginal vignette of leaves in one corner',
      'a faint hand-written annotation in the lower right corner (no readable text)',
      'a subtle wash of background landscape (distant hills, low horizon)',
      'a single dried-flower study in the corner',
      'a stippled empty background, archival emptiness',
    ],
    render: [
      'denser cross-hatching technique',
      'looser softer watercolor wash dominant',
      'bolder ink contour line',
      'finer stipple shading on the cheek',
      'gentle dry-brush highlights along the brow',
    ],
  },
} satisfies PetFilterCartridge['imagePrompt'];

export const naturalistCartridge: PetFilterCartridge = {
  id: 'naturalist-society',
  gameId: 'pet-filter',
  routeFamily: 'identity-transformation-archive',
  identityLoop: {
    inputMode: 'portrait-reference',
    interpretationMode: 'species-classification',
    artifactMode: 'natural-history-plate',
    archiveMode: 'public-bestiary',
  },
  curator: {
    classifySystemIntro:
      'You are a 19th-century natural history society scholar examining an unknown subject. Classify them under ONE of these twenty known orders. Each order has character:',
    outputRules:
      'Output STRICT JSON only, no markdown fences, no commentary:\n' +
      '{"species": "<id>", "verdict": "<one elegant Victorian-voice sentence>"}\n\n' +
      'The verdict is a single sentence under 24 words in the voice of a 19th-c. naturalist (e.g. "The faint set of the brow betrays..." or "Something in the bearing recalls..."). Do NOT use second person ("you"). Refer to the subject as "the subject" or "this specimen". No quotes inside the verdict.',
    judgmentSystem:
      'You are a 19th-century natural history society scholar writing a verdict for an unknown subject. Output ONE single elegant sentence in the voice of a Victorian naturalist (e.g. "The faint set of the brow betrays...", "Something in the bearing recalls..."). Do NOT reference photographs, AI, or modern concepts. Do NOT use second person ("you"). Refer to the subject as "the subject" or "this specimen". Maximum 24 words. Plain text, no quotes.',
  },
  imagePrompt: naturalistImagePrompt,
  copy: {
    overrides: {
      en: {
        brand_mark: 'natural history society · vol. I',
        plate_header_frontispiece: 'Frontispiece',
        plate_header_default: 'Field Station',
        plate_header_bestiary: 'Bestiary',
        plate_header_processing: 'Plate — pending',
        plate_header_result: 'Plate',
        plate_header_wall: 'Specimens collected',
        front_house: 'ALTERU',
        front_year: 'MMXXVI',
        front_book_title: 'Transfiguration',
        front_book_sub: 'or, How One May Be Reclassified',
        front_credit_label: 'plate by',
        front_cta_open: 'Open the volume',
        front_cta_archive: 'Browse the archive',
        front_example_stamp: 'SPECIMEN — example',
        front_tap_hint: 'tap the plate · or open below',
        bestiary_dropcap: 'T',
        bestiary_title: 'he Twelve Known Orders',
        bestiary_sub: 'As catalogued by the Society. Tap a plate to inspect.',
        bestiary_link: 'Browse all twelve ›',
        hero_dropcap: 'A',
        hero_title: ' Curious Reclassification',
        hero_sub: 'Submit a likeness — the Society alone will determine which of the twelve known orders you most resemble.',
        upload_label: 'Subject of study',
        upload_cta: 'Submit a different likeness',
        upload_cta_no_avatar: 'Submit a likeness',
        upload_replace: 'Submit a different likeness',
        upload_caption_empty: 'No likeness on file — please submit one.',
        upload_caption_ready: 'Specimen received.',
        upload_caption_avatar_default: 'Your portrait, on file with the Society.',
        upload_tap_hint: 'tap to upload',
        catalog_note: 'You need not choose. The Society will study your likeness and determine your place among these.',
        cta_transfigure: 'Let the Society reclassify me',
        cta_need_specimen: 'Submit a likeness first',
        cta_wall: 'Society archive',
        cta_new_pet: 'Reclassify again',
        cta_back_to_picker: 'Back',
        cta_back_to_wall: 'Return to archive',
        cta_share: 'Inscribe & share',
        cta_share_again: 'Share again',
        share_copied: 'copied — paste anywhere',
        cta_petition: 'Petition for re-examination',
        cta_petition_used: 'One petition remaining',
        cta_petition_final: 'The Society stands by its judgment',
        discard_plate: 'Discard this specimen',
        discard_confirm: 'Tap again to confirm',
        daily_recent: 'The Society received your last application',
        daily_next: 'A new examination tomorrow',
        proc_step_reading: 'Measuring the specimen',
        proc_step_morphing: 'Consulting the orders',
        proc_step_rendering: 'Drafting the plate',
        proc_step_settling: 'Affixing the leaf',
        proc_fineprint: 'Do not refresh — engraving in progress.',
        proc_cancel: 'Abandon the engraving',
        proc_considering: '— The Society considers —',
        proc_elapsed: 'elapsed',
        proc_est_total: 'est. total',
        result_subhead: 'The Society has determined this subject to be a',
        result_below_image: 'engraved for the Society archive',
        result_author_by: 'a plate by',
        result_judgment_signature: 'the Society',
        wall_heading: 'The Society Archive',
        wall_sub: 'Specimens recently catalogued by other naturalists.',
        wall_empty: 'No entries yet. The archive awaits its first plate.',
        wall_alone: 'No other naturalist has submitted yet. You may have the archive to yourself for a moment.',
        notes_heading: 'Marginalia',
        notes_sub: 'Notes inscribed in the margin by other naturalists.',
        notes_empty: 'No notes yet. Be the first to inscribe one.',
        note_placeholder: 'Leave a note in the margin…',
        note_send: 'Inscribe',
        note_you: 'you',
        note_signed_in_only: 'Open in AlterU to leave a note.',
        download_alteru: 'Get AlterU',
      },
      zh: {
        brand_mark: '博物学会 · 卷一',
        plate_header_frontispiece: '扉页',
        plate_header_default: '田野工作站',
        plate_header_bestiary: '物种图鉴',
        plate_header_processing: '图版 — 拟定中',
        plate_header_result: '图版',
        plate_header_wall: '收集到的标本',
        front_house: 'ALTERU 博物学会',
        front_year: '丙午年',
        front_book_title: '《变形术》',
        front_book_sub: '或：一种现代重新分类法',
        front_credit_label: '图版',
        front_cta_open: '开卷',
        front_cta_archive: '档案室',
        front_example_stamp: '示例 — 非用户标本',
        front_tap_hint: '轻触图版 · 或点下方开卷',
        bestiary_dropcap: '十',
        bestiary_title: '二目全录',
        bestiary_sub: '学会所定。轻触图版以详阅。',
        bestiary_link: '翻阅十二目 ›',
        hero_dropcap: '奇',
        hero_title: '妙的重新分类',
        hero_sub: '提交一张肖像 — 学会将独自判定你最贴近十二目中的哪一种。',
        upload_label: '研究对象',
        upload_cta: '换一张肖像',
        upload_cta_no_avatar: '提交肖像',
        upload_replace: '换一张肖像',
        upload_caption_empty: '档案中尚无肖像 — 请提交一张。',
        upload_caption_ready: '标本已收到。',
        upload_caption_avatar_default: '你的肖像，已在学会档案中。',
        upload_tap_hint: '轻触上传',
        catalog_note: '你无需挑选。学会将查阅你的肖像，判定你属于这十二目之一。',
        cta_transfigure: '请学会为我重新分类',
        cta_need_specimen: '请先提交肖像',
        cta_wall: '学会档案',
        cta_new_pet: '再分类一次',
        cta_back_to_picker: '返回',
        cta_back_to_wall: '回档案室',
        cta_share: '题字并分享',
        cta_share_again: '再分享一次',
        share_copied: '已复制 — 可粘贴到任意处',
        cta_petition: '申请二审',
        cta_petition_used: '尚余一次申请',
        cta_petition_final: '学会维持原判',
        discard_plate: '丢弃此标本',
        discard_confirm: '再次轻触以确认',
        daily_recent: '学会近日已收到你的申请',
        daily_next: '明日再行查阅',
        proc_step_reading: '测量标本',
        proc_step_morphing: '查阅诸纲目',
        proc_step_rendering: '绘制图版',
        proc_step_settling: '装订书页',
        proc_fineprint: '请勿刷新 — 雕版进行中。',
        proc_cancel: '中止雕版',
        proc_considering: '— 学会逐一考虑 —',
        proc_elapsed: '已用时',
        proc_est_total: '预计总时长',
        result_subhead: '学会判定此对象属于',
        result_below_image: '入档于学会档案',
        result_author_by: '图版作者',
        result_judgment_signature: '学会',
        wall_heading: '学会档案',
        wall_sub: '其他博物学家近期收录的标本。',
        wall_empty: '还没有人收录。等你来做第一页。',
        wall_alone: '暂无其他博物学家投稿。这片刻档案室归你独享。',
        notes_heading: '旁注',
        notes_sub: '其他博物学家在页边留下的批注。',
        notes_empty: '还没有批注。来写下第一条。',
        note_placeholder: '在页边留一句…',
        note_send: '题写',
        note_you: '你',
        note_signed_in_only: '在 AlterU 中打开即可留言。',
        download_alteru: '下载 AlterU',
      },
    },
  },
  frontispiece: {
    liveRotationMs: 6500,
    demoRotationMs: 3200,
    liveAuthorFallback: 'anonymous',
    selfAuthorName: 'You',
    demoPortraits: [
      { asset: 'demo_pet_cat.jpg', petId: 'cat' },
      { asset: 'demo_pet_capybara.jpg', petId: 'capybara' },
      { asset: 'demo_pet_octopus.jpg', petId: 'octopus' },
    ],
  },
  processing: {
    considerationRotationMs: 3200,
  },
  speciesPack: createNaturalistSpeciesPack(naturalistImagePrompt),
  social: {
    reactionOrder: ['heart', 'fire', 'mind', 'eye'],
    reactionAriaLabels: {
      heart: 'love this specimen',
      fire: 'struck by this specimen',
      mind: 'marvel at this specimen',
      eye: 'keep an eye on this specimen',
    },
    reactionNotifyTemplates: {
      heart: '{sender_name} loved your specimen.',
      fire: '{sender_name} was struck by your specimen.',
      mind: '{sender_name} marvelled at your specimen.',
      eye: '{sender_name} kept an eye on your specimen.',
    },
    reactionImagePromptSuffix: 'field-guide plate, 19th-c. natural-history engraving',
  },
  archive: {
    statsAriaLabel: 'archive statistics',
    statsLabels: {
      onFile: 'on file',
      today: 'today',
      orders: 'orders',
    },
    platePrefix: 'Pl.',
    selfByline: 'your specimen',
    authorPrefix: 'collected by',
    tileSelfByline: 'yours',
    tileAuthorPrefix: 'by',
    authorFallback: 'collector',
    relativeTime: {
      justNow: 'just now',
      minuteAgoSuffix: 'm ago',
      hourAgoSuffix: 'h ago',
      dayAgoSuffix: 'd ago',
    },
  },
  locked: [
    'portrait/reference input -> species classification -> AI hybrid plate -> verdict card',
    'personal save, public bestiary/archive, reactions, notes, and share/open-in-app flow',
    'human-eye identity anchor and image safety/recognizability constraints',
  ],
  cartridgeCanChange: [
    'taxonomy and species names',
    'curator persona and verdict voice',
    'plate/artifact style',
    'archive framing and reaction labels',
  ],
};
